# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jgiletta/Documents/Capacitaciones/spl_2023/ws1_design_flow/lab2_gpio/lab2_gpio.srcs/sources_1/bd/lab_gpio_in_out/ip/lab_gpio_in_out_processing_system7_0_0/lab_gpio_in_out_processing_system7_0_0.xci
# IP: The module: 'lab_gpio_in_out_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jgiletta/Documents/Capacitaciones/spl_2023/ws1_design_flow/lab2_gpio/lab2_gpio.srcs/sources_1/bd/lab_gpio_in_out/ip/lab_gpio_in_out_processing_system7_0_0/lab_gpio_in_out_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_gpio_in_out_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/jgiletta/Documents/Capacitaciones/spl_2023/ws1_design_flow/lab2_gpio/lab2_gpio.srcs/sources_1/bd/lab_gpio_in_out/ip/lab_gpio_in_out_processing_system7_0_0/lab_gpio_in_out_processing_system7_0_0.xci
# IP: The module: 'lab_gpio_in_out_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jgiletta/Documents/Capacitaciones/spl_2023/ws1_design_flow/lab2_gpio/lab2_gpio.srcs/sources_1/bd/lab_gpio_in_out/ip/lab_gpio_in_out_processing_system7_0_0/lab_gpio_in_out_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_gpio_in_out_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
