# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab_gpio_constr.xdc

# Block Designs: bd/lab_gpio_in_out/lab_gpio_in_out.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out || ORIG_REF_NAME==lab_gpio_in_out} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_processing_system7_0_0/lab_gpio_in_out_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_processing_system7_0_0 || ORIG_REF_NAME==lab_gpio_in_out_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_axi_gpio_0_0/lab_gpio_in_out_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_axi_gpio_0_0 || ORIG_REF_NAME==lab_gpio_in_out_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_xbar_0/lab_gpio_in_out_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_xbar_0 || ORIG_REF_NAME==lab_gpio_in_out_xbar_0} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_ps7_0_axi_periph_0/lab_gpio_in_out_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_gpio_in_out_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_rst_ps7_0_100M_0/lab_gpio_in_out_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_gpio_in_out_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_axi_gpio_0_1/lab_gpio_in_out_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_axi_gpio_0_1 || ORIG_REF_NAME==lab_gpio_in_out_axi_gpio_0_1} -quiet] -quiet

# IP: bd/lab_gpio_in_out/ip/lab_gpio_in_out_auto_pc_0/lab_gpio_in_out_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_gpio_in_out_auto_pc_0 || ORIG_REF_NAME==lab_gpio_in_out_auto_pc_0} -quiet] -quiet

# XDC: bd/lab_gpio_in_out/lab_gpio_in_out_ooc.xdc
