# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rtos_example/rtos_example.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtos_example || ORIG_REF_NAME==rtos_example} -quiet] -quiet

# IP: bd/rtos_example/ip/rtos_example_axi_gpio_0_0/rtos_example_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtos_example_axi_gpio_0_0 || ORIG_REF_NAME==rtos_example_axi_gpio_0_0} -quiet] -quiet

# IP: bd/rtos_example/ip/rtos_example_processing_system7_0_1/rtos_example_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtos_example_processing_system7_0_1 || ORIG_REF_NAME==rtos_example_processing_system7_0_1} -quiet] -quiet

# IP: bd/rtos_example/ip/rtos_example_auto_pc_0/rtos_example_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtos_example_auto_pc_0 || ORIG_REF_NAME==rtos_example_auto_pc_0} -quiet] -quiet

# IP: bd/rtos_example/ip/rtos_example_ps7_0_axi_periph_0/rtos_example_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtos_example_ps7_0_axi_periph_0 || ORIG_REF_NAME==rtos_example_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/rtos_example/ip/rtos_example_rst_ps7_0_100M_0/rtos_example_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rtos_example_rst_ps7_0_100M_0 || ORIG_REF_NAME==rtos_example_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/rtos_example/rtos_example_ooc.xdc
